### ISSUE TITLE
oral health - table labels

### ISSUE THREAD

**Issue by rgentlem** [ccb-hms/NHANES-metadata#1]
For variables like this one: LOA: Max R(2B) MdL FGM-CEJ(mm)
found in this table:
https://wwwn.cdc.gov/nchs/nhanes/2011-2012/OHXPER_G.htm

the table label (not sure if we have those, but we should probably get a DB table with them)
Oral Health - Periodontal (OHXPER_G)

and so it seems like we could use that information - ie Oral Health and Periodontal as a minimum ontological mapping (not sure if any of our ontologies have dentistry phenotypes)

not sure how we should best address this information in our phenotype mapping project.  
It might be best to create a mapping by hand for Oral Health - Periodontal  and put that into the DB (some method for identifying questions that we don't want to send out for phenotype mapping and some mechanism for merging our internal values with mapped values ....might be the most pragmatic).

**Comment by paynejason** [comment]
As of a few months ago, manual mappings were made by two dental specialists (Catherine Hayes and Steffany Chamut) and processed in a separate [repository](https://github.com/ccb-hms/nhanes-oral-health/) that is currently CCB only. 
However, steps are being taken to combine that repository with this one, at which point this issue will be closed.

**Comment by paynejason** [comment]
Tables for the synonyms and the [human-verified mappings](https://github.com/ccb-hms/NHANES-metadata/blob/master/ontology-mappings/nhanes_oral_health_mappings.tsv) have been added.
