### ISSUE TITLE
Tables in DB missing from metadata

### ISSUE THREAD

**Issue by deepayan** [ccb-hms/NHANES-metadata#11]
The following tables are in the database (can be retrieved using `nhanes(name)`) but do not appear in the metadata table `Metadata.QuestionnaireDescriptions`.

The commonality seems to be that their `nhanesCodebook()` is also broken. 

  - [RXQ\_DRUG](https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/RXQ_DRUG.htm) - drug table (no SEQN)
  - [DRXFMT\_B](https://wwwn.cdc.gov/Nchs/Nhanes/2001-2002/DRXFMT_B.htm) - TOC has no codebook 
  - [DRXFMT](https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/DRXFMT.htm) - TOC has no codebook
  - [DRXFCD\_J](https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/DRXFCD_J.htm) - TOC has no codebook
  - [DRXFCD\_I](https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/DRXFCD_I.htm) - TOC has no codebook
  - [SSNH4THY](https://wwwn.cdc.gov/Nchs/Nhanes/2001-2002/SSNH4THY.htm) - wrong auto-generated URL, should have had suffix `_B`
  - [SSHCV\_E](https://wwwn.cdc.gov/Nchs/Nhanes/2007-2008/SSHCV_E.htm) - looks OK (except variable `SSASCR3`?)
  - [SSDFS\_A](https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/SSDFS_A.htm) - looks OK
  - [POOLTF\_E](https://wwwn.cdc.gov/Nchs/Nhanes/2007-2008/POOLTF_E.htm) - TOC has no codebook
  - [POOLTF\_D](https://wwwn.cdc.gov/Nchs/Nhanes/2005-2006/POOLTF_D.htm) - TOC has no codebook
  - [SSCMVG\_A](https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/SSCMVG_A.htm) - looks OK
  - [SSCARD\_A](https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/SSCARD_A.htm) - looks OK
  - [SSBNP\_A](https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/SSBNP_A.htm) - looks OK
  - [SSANA2\_A](https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/SSANA2_A.htm) - looks OK
  - [SSANA\_A](https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/SSANA_A.htm) - looks OK
  - [SSAGP\_J](https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/SSAGP_J.htm) - looks OK
  - [SSAGP\_I](https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/SSAGP_I.htm) - looks OK
  - [PFC\_POOL](https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/PFC_POOL.htm) - page missing
  - [DSPI](https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/DSPI.htm) - looks OK, but no SEQN
  - [FOODLK\_D](https://wwwn.cdc.gov/Nchs/Nhanes/2005-2006/FOODLK_D.htm) - TOC has no codebook
  - [DSII](https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/DSII.htm) - looks OK
  - [FOODLK\_C](https://wwwn.cdc.gov/Nchs/Nhanes/2003-2004/FOODLK_C.htm) - ?? (lookup table)
  - [DSBI](https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/DSBI.htm) - looks OK, but no SEQN
  - [VARLK\_D](https://wwwn.cdc.gov/Nchs/Nhanes/2005-2006/VARLK_D.htm) - ?? (lookup table)
  - [VARLK\_C](https://wwwn.cdc.gov/Nchs/Nhanes/2003-2004/VARLK_C.htm) - ?? (lookup table)
  - [SSUCSH\_A](https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/SSUCSH_A.htm) - looks OK
  - [SSTROP\_A](https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/SSTROP_A.htm) - looks OK

**Comment by rsgoncalves** [comment]
What seems to be happening with these is that `nhanesA::nhanesTables()` isn't returning them—a bug in nhanesA likely.

For example, the table `SSANA_A` isn't among the 1999-2000 survey tables obtained via:
```{r}
tables_99 <- nhanesTables(data_group="LAB", year=1999, details=TRUE, includerdc=TRUE)
```

**Comment by deepayan** [comment]
Thanks, I'll take a closer look. Interestingly, 

```r
nhanesTables(data_group="LAB", year=1999, details=TRUE, includerdc=TRUE)
```

run without the DB finds a few more tables, but none of the ones listed above:

```
"LAB05"    "L11_2_R"  "L09RDC_A" "L05RDC_A" "L06_2_00" "VID_2_00" "L10_2_00" "L18_2_00" "L13_2_R"  "L19_2_R" "L16_2_R"  "L25_2_R"  "VIT_2_R"
```

**Comment by deepayan** [comment]
So, it looks like 

```r
nhanesTables(data_group="LAB", year=1999, details=TRUE, includerdc=TRUE)
```

doesn't include `SSANA_A` because [it and its variables](https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/SSANA_A.htm) are not included in

<https://wwwn.cdc.gov/Nchs/Nhanes/search/variablelist.aspx?Component=Laboratory&CycleBeginYear=1999>

which is where `nhanesTables()` looks. This looks like a bug in the NHANES website. 

I am not sure how we can work around this. Changing `nhanesTables()` doesn't really make sense. We probably need to work off a different source of tables (like the `nhanesA::nhanesManifest()` recently added by @rgentlem).

**Comment by rsgoncalves** [comment]
Thank you @deepayan. Using nhaneManifest() we now have all the listed tables in the metadata release https://github.com/ccb-hms/NHANES-metadata/releases/tag/v3.8.0 (to be included in the NHANES DB in the next iteration).
