### ISSUE TITLE
Codebooks for P_ tables are missing from Metadata.QuestionnaireDescriptions and Metadata.QuestionnaireVariables

### ISSUE THREAD

**Issue by Genoa-HMS** [ccb-hms/NHANES-metadata#14]
Migrating this issue from NHANES to NHANES-metadata. See https://github.com/ccb-hms/NHANES/issues/93 and https://github.com/ccb-hms/NHANES/issues/94 for original issues.

1. P tables are not included in Metadata.QuestionnaireDescriptions, and we need them in the table for searching operations. eg nhanesTables('DIET', 'P')

2. The variables from P_ tables are not in the Metadata.QuestionnaireVariables, we need them to implement Codebooks.

**Comment by Genoa-HMS** [comment]
From Robert in October: 
i think i sent you code for this a few weeks ago
there is a non-canonical path - but i think it works
 these cover 4 years ….

**Comment by rsgoncalves** [comment]
The metadata about P tables are included in the latest release https://github.com/ccb-hms/NHANES-metadata/releases/tag/v3.7.0. If I recall correctly I announced and described this release in our last Epi meeting.
