### ISSUE TITLE
Identify new patterns of non-phenotypes in low-scored mappings

### ISSUE THREAD

**Issue by paynejason** [ccb-hms/NHANES-metadata#16]
Iteratively go through the bottom 1000 mappings from text2term and identity new patterns that identify non-phenotypes and phenotypes. Update text2term to map these.

**Comment by rsgoncalves** [comment]
The two broad goals of this task are to identify:
- patterns of non-phenotypes
- patterns of variables that could be better represented (e.g. severity of a disease)
