### ISSUE TITLE
please use FALSE and TRUE exclusively in the .tsv files

### ISSUE THREAD

**Issue by rgentlem** [ccb-hms/NHANES-metadata#29]
Hi,
  It is easier, when reading these into R if you use FALSE and TRUE, rather than False and True, as the former are keys
that are used to make the column a logical vector rather than a character vector.
You do use these in the UseConstraints column, but for some reason use False and True in the IsPhenotype and OntologyMapped columns.
  In some sense, no matter what you should always use the same character strings for true and false, throughout a table.

 thanks

**Comment by rsgoncalves** [comment]
This should be fixed now in [v3.9.1](https://github.com/ccb-hms/NHANES-metadata/releases/tag/v3.9.1).
