### ISSUE TITLE
Decouple ontology mapping details from `nhanes_variables.tsv` to a separate table

### ISSUE THREAD

**Issue by rsgoncalves** [ccb-hms/NHANES-metadata#32]
Move details used such as `ProcessedText` and `Tags` used for ontology mapping to a new table (in `ontology-mappings` folder), keeping variable and table identifiers to allow lookups.

**Comment by paynejason** [comment]
The table as it was is now stored in the file "nhanes_variables_processed.tsv", while the original "nhanes_variables.tsv" excludes "ProcessedText" and "Tags".
