### ISSUE TITLE
skipped tables list

### ISSUE THREAD

**Issue by rgentlem** [ccb-hms/NHANES-metadata#6]
Hi,
  I am working with the release version of the NHANES docker.  I don't seem to be able to find the list of files that were excluded.
Is there a list (which should go with the container) of files we just won't download due to size or other constraints?
Is that going to come in a future release?
thanks
 Robert

**Comment by rsgoncalves** [comment]
At the moment we generate a .tsv (https://github.com/ccb-hms/NHANES-metadata/blob/master/metadata/missing_codebooks.tsv) containing the table-variable ID pairs that we could not obtain codebooks for. This table isn't currently included in the Docker release, but can be in the future. Maybe there already is a similar table or log of sorts in the container that we could tack on our list— is there @sam-pullman?

**Comment by sam-pullman** [comment]
Are you referring to the excluded tables manifest? This would be the [Metadata].ExcludedTables table in the db.
